name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000
      SWAPI_URL: 'https://swapi.py4e.com/api'

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install frontend dependencies
        run: npm install
        working-directory: apps/frontend

      - name: Install backend dependencies
        run: npm install
        working-directory: apps/backend

      - name: Run Prettier check
        run: npx prettier --check .

      - name: Run frontend tests
        run: npm run test
        working-directory: apps/frontend

      - name: Run backend tests
        run: npm run test
        working-directory: apps/backend

      - name: Build frontend
        run: npm run build
        working-directory: apps/frontend

      - name: Build backend
        run: npm run build
        working-directory: apps/backend
