name: CI

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install frontend dependencies
        run: cd apps/frontend && npm install

      - name: Install backend dependencies
        run: cd apps/backend && npm install

      - name: Run Prettier check
        run: npx prettier . --check

      - name: Run frontend tests
        run: npm run test --workspace=apps/frontend

      - name: Run backend tests
        run: npm run test --workspace=apps/backend

      - name: Build frontend
        run: npm run build --workspace=apps/frontend

      - name: Build backend
        run: npm run build --workspace=apps/backend
